apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: app-config-rhdh
    dynamicPluginsConfigMapName: dynamic-plugins
    extraEnvs:
      # Seems to be needed for the kubernetes api interaction
      # since RHPDS cluster is using self-signed certificates
      # for the api server
      envs:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
      secrets:
        - name: gitlab-token
        - name: argocd-password
        - name: kubernetes-sa-token
        - name: oauth-client
        - name: backend-secret
        - name: backstage-orchestrator-token
        - name: aap-credentials
        - name: ado-credentials
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
  deployment:
    patch:
      spec:
        template:
          spec:
            containers:
              - env:
                  - name: VALIDATION_PROVIDER
                    value: vllm
                  - name: VALIDATION_MODEL_NAME
                    value: qwen3-14b
                envFrom:
                  - secretRef:
                      name: llama-stack-secrets
                image: 'quay.io/redhat-ai-dev/llama-stack:0.1.1'
                name: llama-stack
                volumeMounts:
                  - mountPath: /app-root/.llama
                    name: shared-storage
                  - mountPath: /app-root/embeddings_model
                    name: rag-data-volume
                    subPath: embeddings_model
                  - mountPath: /app-root/vector_db/rhdh_product_docs
                    name: rag-data-volume
                    subPath: rhdh_product_docs
              - image: 'quay.io/lightspeed-core/lightspeed-stack:dev-20251021-ee9f08f'
                name: lightspeed-core
                volumeMounts:
                  - mountPath: /app-root/lightspeed-stack.yaml
                    name: lightspeed-stack
                    subPath: lightspeed-stack.yaml
                  - mountPath: /tmp/data/feedback
                    name: shared-storage
                  - mountPath: /tmp/data/transcripts
                    name: shared-storage
                  - mountPath: /tmp/data/conversations
                    name: shared-storage
            initContainers:
              - name: init-rag-data
                image: 'quay.io/redhat-ai-dev/rag-content:release-1.8-lcs'
                command:
                  - "sh"
                  - "-c"
                  - "echo 'Copying RAG data...'; cp -r /rag/vector_db/rhdh_product_docs /data/ && cp -r /rag/embeddings_model /data/ && echo 'Copy complete.'"
                volumeMounts:
                  - mountPath: /data
                    name: rag-data-volume
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
              - configMap:
                  name: lightspeed-stack
                name: lightspeed-stack
              - emptyDir: {}
                name: shared-storage
              - emptyDir: {}
                name: rag-data-volume
  database:
    enableLocalDb: true
