apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llama-stack-secrets
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: llama-stack-secrets
    creationPolicy: Owner
  data:
    - secretKey: VLLM_URL
      remoteRef:
        key: secrets/litellm/credentials
        property: base_url
    - secretKey: VLLM_API_KEY
      remoteRef:
        key: secrets/litellm/credentials
        property: api_key
    - secretKey: ENABLE_VLLM
      remoteRef:
        key: secrets/litellm/credentials
        property: enable_vllm
    - secretKey: ENABLE_OLLAMA
      remoteRef:
        key: secrets/litellm/credentials
        property: enable_ollama
    - secretKey: SAFETY_MODEL
      remoteRef:
        key: secrets/litellm/credentials
        property: safety_model
    - secretKey: SAFETY_URL
      remoteRef:
        key: secrets/litellm/credentials
        property: safety_url
    - secretKey: SAFETY_API_KEY
      remoteRef:
        key: secrets/litellm/credentials
        property: safety_api_key
