apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llama-stack-secrets
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: llama-stack-secrets
    creationPolicy: Owner
    template:
      data:
        VLLM_URL: "{{ "{{ .base_url }}" }}"
        VLLM_API_KEY: "{{ "{{ .api_key }}" }}"
        ENABLE_VLLM: "true"
        ENABLE_OLLAMA: ""
        SAFETY_MODEL: "qwen3-14b"
        SAFETY_URL: "{{ "{{ .base_url }}" }}"
        SAFETY_API_KEY: "{{ "{{ .api_key }}" }}"
  data:
    - secretKey: base_url
      remoteRef:
        key: secrets/litellm/credentials
        property: base_url
    - secretKey: api_key
      remoteRef:
        key: secrets/litellm/credentials
        property: api_key
